
name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  API_GATEWAY_STAGE: prod

jobs:
  deploy:
    name: build and deploy prod docker image
    runs-on: be
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.PROD_ENV }}
          EOF
      - name: docker build
        run: docker build -t backend-prod .
        
      - name: Docker stop and remove
        run: |
          CONTAINER_NAME="backend-prod-c"

          if [[ "$(docker inspect -f '{{.State.Running}}' $CONTAINER_NAME 2>/dev/null)" == "true" ]]; then
            echo "Stopping Docker container $CONTAINER_NAME"
            docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME && sudo docker system prune -f
          else
            echo "Docker container $CONTAINER_NAME is not running"
          fi
      
      - name: Docker start 
        run: docker run -d --name backend-prod-c -p 3002:3005 backend-prod
        # run: docker run -d --name backend-prod-c -p 3002:3005   --log-driver=awslogs   --log-opt awslogs-group=zeeinvoices   --log-opt awslogs-stream=zeeinvoices-prod   --log-opt awslogs-region=eu-north-1    --restart always backend-prod
      - name: Docker show logs 
        run: sleep 50 && docker logs backend-prod-c

      - name: Clean up interim docker
        run: docker image prune -f && docker container prune -f

