name: Deploy qa branch

on:
  push:
    branches:
      - qa

env:
  API_GATEWAY_STAGE: qa

jobs:
  deploy:
    name: Build and deploy qa Docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.QA_ENV }}
          EOF
      - name: Docker build
        run: docker build -t backend-qa .
        
      - name: Docker stop and remove
        run: |
          CONTAINER_NAME="backend-qa-c"
          if [[ "$(docker inspect -f '{{.State.Running}}' $CONTAINER_NAME 2>/dev/null)" == "true" ]]; then
            echo "Stopping Docker container $CONTAINER_NAME"
            docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME && sudo docker system prune -f
          else
            echo "Docker container $CONTAINER_NAME is not running"
          fi
      
      - name: Docker start 
        # run: docker run -d --name backend-qa-c -p 3005:3005 backend-qa
        run: docker run -d --name backend-qa-c -p 3005:3005   --log-driver=awslogs   --log-opt awslogs-group=zeeinvoices   --log-opt awslogs-stream=zeeinvoices-qa-staging  --log-opt awslogs-region=eu-north-1    --restart always backend-qa

    
      - name: Docker show logs 
        run: sleep 50 && docker logs backend-qa-c

      - name: Clean up interim Docker
        run: docker image prune -f && docker container prune -f
